apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::890752002226:role/eksctl-ibro-project4-nodegroup-ng-NodeInstanceRole-1VYWAC8HVWFKO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::890752002226:role/UdacityProject4KubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T09:59:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1592"
  uid: 15ef3dda-9c44-4fd3-a106-d31b8c3845b2
